name: Update backlinks

on:
  gollum:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - uses: actions/checkout@v2
        with:
          repository: sander/note-link-janitor
          path: note-link-janitor
      - name: Build note-link-janitor
        run: cd note-link-janitor && yarn install && yarn run build
      - name: Update backlinks
        run: |
          cd wiki
          ../note-link-janitor/dist/index.js .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update backlinks"
          git push

